#!/bin/bash

exec docker run --rm \
    --privileged \
    -e DISPLAY=unix$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
    -v /mnt/docker-data/configs/virtualbox:/home/vu/VirtualBox \
    --name virtualbox \
    thenewvu/virtualbox
